just disable cross-compiling for now

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -28,14 +28,14 @@ jobs:
             target: x86_64
           - runner: ubuntu-latest
             target: x86
-          - runner: ubuntu-latest
-            target: aarch64
-          - runner: ubuntu-latest
-            target: armv7
-          - runner: ubuntu-latest
-            target: s390x
-          - runner: ubuntu-latest
-            target: ppc64le
+          # - runner: ubuntu-latest
+          #   target: aarch64
+          # - runner: ubuntu-latest
+          #   target: armv7
+          # - runner: ubuntu-latest
+          #   target: s390x
+          # - runner: ubuntu-latest
+          #   target: ppc64le
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
@@ -48,6 +48,8 @@ jobs:
             (
               set -exfv
               if [ -n "${TARGET_SYSROOT:-}" ]; then
+                echo "I can't figure out cross compiling with alsa.  Might disable it with a feature or something instead."
+                exit 1
                 export DEBIAN_FRONTEND=noninteractive
                 apt update
                 apt install -y pkg-config
@@ -55,9 +57,6 @@ jobs:
                 yum install -y pkgconfig alsa-lib-devel
               fi
             )
-            if [ -n "${TARGET_SYSROOT:-}" ]; then
-              export "PKG_CONFIG_SYSROOT_DIR=$TARGET_SYSROOT"
-            fi
           target: ${{ matrix.platform.target }}
           args: --release --out dist --find-interpreter -m ./python-libdaw/Cargo.toml
           sccache: 'true'
